# Generated by Django 4.2.29 on 2026-04-03 19:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('interest', '0005_category_created_at_category_created_by_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserModerationStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('warning_count', models.PositiveIntegerField(default=0)),
                ('is_blocked', models.BooleanField(default=False)),
                ('blocked_at', models.DateTimeField(blank=True, null=True)),
                ('blocked_reason', models.TextField(blank=True, null=True)),
                ('admin_notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='moderation_status', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
                'indexes': [models.Index(fields=['user', '-updated_at'], name='moderation__user_id_31d73a_idx'), models.Index(fields=['is_blocked', '-updated_at'], name='moderation__is_bloc_ade6b7_idx')],
            },
        ),
        migrations.CreateModel(
            name='ModerationEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_type', models.CharField(choices=[('chat_message', 'Chat Message'), ('post', 'Post'), ('comment', 'Comment'), ('category_proposal', 'Category Proposal')], max_length=30)),
                ('content_id', models.PositiveIntegerField(blank=True, null=True)),
                ('content_text', models.TextField(blank=True, help_text='Content that was moderated', null=True)),
                ('violation_type', models.CharField(blank=True, choices=[('safety', 'Safety Violation'), ('spam', 'Spam'), ('unrelated', 'Unrelated Category/Topic')], max_length=30, null=True)),
                ('decision', models.CharField(choices=[('approved', 'Approved'), ('rejected', 'Rejected'), ('pending_review', 'Pending Review')], max_length=20)),
                ('rejection_reason', models.TextField(blank=True, null=True)),
                ('warning_issued', models.BooleanField(default=False)),
                ('auto_blocked', models.BooleanField(default=False)),
                ('ai_model_used', models.CharField(blank=True, help_text='OpenAI model used for moderation', max_length=50, null=True)),
                ('ai_flags', models.JSONField(blank=True, default=dict, help_text='AI moderation API flags')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='moderation_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='moderation__user_id_4404ff_idx'), models.Index(fields=['content_type', '-created_at'], name='moderation__content_3137f2_idx'), models.Index(fields=['decision', '-created_at'], name='moderation__decisio_b89627_idx'), models.Index(fields=['violation_type', '-created_at'], name='moderation__violati_9ee3ed_idx')],
            },
        ),
        migrations.CreateModel(
            name='CategoryProposal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proposal_type', models.CharField(choices=[('category', 'Category'), ('subcategory', 'SubCategory')], max_length=20)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('rejection_reason', models.TextField(blank=True, null=True)),
                ('ai_confidence', models.JSONField(blank=True, default=dict, help_text='AI relevance detection confidence scores')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('admin_notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parent_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subcategory_proposals', to='interest.category')),
                ('proposer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_proposals', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_proposals', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['proposer', '-created_at'], name='moderation__propose_471f02_idx'), models.Index(fields=['status', '-created_at'], name='moderation__status_d957a5_idx')],
            },
        ),
    ]
