# Generated by Django 4.2.29 on 2026-04-08 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moderation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moderationevent',
            name='content_type',
            field=models.CharField(choices=[('chat_message', 'Chat Message'), ('post', 'Post'), ('comment', 'Comment'), ('marketplace_product', 'Marketplace Product'), ('category_proposal', 'Category Proposal')], max_length=30),
        ),
    ]
