# Generated by Django 4.2.28 on 2026-02-05 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0002_communityinvitation_communityjoinrequest_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='community',
            name='members_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
