# Generated by Django 4.2.29 on 2026-04-08 18:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0004_community_status_and_rejection_reason'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='community',
            new_name='community_c_status_078e14_idx',
            old_name='community_co_status_5f206a_idx',
        ),
    ]
