# Generated by Django 4.2.28 on 2026-02-05 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0007_add_shared_from_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='video_url',
            field=models.URLField(blank=True, help_text='Link to external video (YouTube, Vimeo, etc.)', null=True),
        ),
    ]
