# Generated by Django 4.2.28 on 2026-03-08 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0008_post_video_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='rejection_reason',
            field=models.TextField(blank=True, help_text='Reason for rejection if the post status is "rejected"', null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('pending', 'Pending')], default='pending', max_length=10),
        ),
    ]
