# Generated by Django 4.2.29 on 2026-04-03 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0009_post_rejection_reason_alter_post_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('like', 'Like'), ('comment', 'Comment'), ('share', 'Share'), ('follow', 'Follow'), ('community_invite', 'Community Invitation'), ('community_join_request', 'Join Request'), ('community_join_approved', 'Join Approved'), ('community_post', 'New Community Post'), ('community_role_changed', 'Role Changed'), ('admin_new_user', 'Admin: New User Signup'), ('admin_new_post', 'Admin: New Post Created'), ('admin_new_community', 'Admin: New Community Created'), ('admin_new_report', 'Admin: New Post Report'), ('admin_new_user_report', 'Admin: New User Report'), ('admin_new_subscription', 'Admin: New Subscription'), ('admin_new_contact', 'Admin: New Contact Message')], max_length=50),
        ),
    ]
