# Generated by Codex on 2026-02-17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0009_alter_usersubscription_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionplan',
            name='billing_cycle',
            field=models.CharField(choices=[('month', 'Monthly'), ('year', 'Yearly')], default='month', max_length=10),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='billing_interval_count',
            field=models.PositiveIntegerField(default=1, help_text='Number of billing cycle units between renewals (e.g. 12 for annual when cycle is month)'),
        ),
    ]
